### ISSUE TITLE
problem with upvm command

### ISSUE THREAD

**Issue by itai257** [ryran/upvm#44]
Hi,
im trying to install the intel onp  by this manual:
https://software.intel.com/en-us/articles/quick-set-up-onp
and when I got to this line:
`upvm fedora-23 --img-size 60G --noconsole -n onp21con --root-password password:mypass -m 8192 -c 8 -w network=default -w bridge=br0 -w bridge=br0 -w bridge=br1`
im getting this error:

>   INFO: HOSTNAME not specified; using 'onp21con.example.com'
>   INFO: Unable to determine native format of chosen template
>   INFO: Using qcow2 for output format (change with --format=raw)
>   INFO: Auto-detected os-variant ('fedora23') was reset to latest ('fedora22') validated by osinfo-query
>   INFO: Initializing libvirt connection to qemu:///session
>   INFO: Starting virt-builder
> [   0.7] Downloading: http://libguestfs.org/download/builder/fedora-23.xz
> [   1.6] Planning how to build this image
> [   1.6] Uncompressing
> [   3.4] Resizing (using virt-resize) to expand the disk to 60.0G
> virt-resize: error: unknown/unavailable method for expanding the xfs 
> filesystem on /dev/sda3
> 
> If reporting bugs, run virt-resize with debugging enabled and include the 
> complete output:
> 
>   virt-resize -v -x [...]
> 
> First execution of 'virt-builder' failed; trying once more ...
> 
> [   0.8] Downloading: http://libguestfs.org/download/builder/fedora-23.xz
> [   1.6] Planning how to build this image
> [   1.6] Uncompressing
> [   3.4] Resizing (using virt-resize) to expand the disk to 60.0G
> virt-resize: error: unknown/unavailable method for expanding the xfs 
> filesystem on /dev/sda3
> 
> If reporting bugs, run virt-resize with debugging enabled and include the 
> complete output:
> 
>   virt-resize -v -x [...]
> virt-builder execution failed; unable to continue
> (Please send rsaw@redhat.com this output)
> 
> Traceback (most recent call last):
>   File "/usr/bin/upvm", line 105, in <module>
>     main()
>   File "/usr/bin/upvm", line 86, in main
>     builder.build()
>   File "/usr/share/upvm/modules/builder.py", line 143, in build
>     subprocess.check_call(cmd)
>   File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['nice', 'virt-builder', 'fedora-23', '--output', '/var/lib/upvm/onp21con.qcow2', '--cache', '/var/cache/upvm', '--hostname', 'onp21con.example.com', '--run', '/tmp/upvm-ifcfgdhcphostname-s6ItYC.sh', '--arch', 'x86_64', '--root-password', 'password:mypass', '--size', '60G', '--format', 'qcow2', '--firstboot', '/tmp/upvm-firstboot-sshkeys-cleanup-njaKA9.sh']' returned non-zero exit status 1

probably this command is doing somthing wrong...
apprciating the help,
Thanks.

**Comment by ryran** [comment]
Hi @itai257 
Assuming you're on a RHEL/Fedora system, you need to install the `libguestfs-xfs` package to add XFS support to `virt-resize`.

**Comment by ryran** [comment]
@itai257 I'm going to assume that advice solved your issue ... if you have further questions, please respond back!
